### ISSUE TITLE
test have to be run from a specific directory 

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-numerrin#5]
pc-p561(~/local/simphony_dev) python -m unittest discover numerrin_wrapper

fails

```
ERROR: test_run_time (numerrin_wrapper.tests.test_numerrin_wrapper.NumerrinWrapperTestCase)
Test that field variable value is changed after
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/W5/fra/local/simphony_dev/simphony-numerrin/numerrin_wrapper/tests/test_numerrin_wrapper.py", line 245, in test_run_time
    'simplemesh.cuds'))
  File "/W5/fra/local/simphony_dev/simphony-common/simphony/io/h5_cuds.py", line 57, in open
    handle = tables.open_file(filename, mode, title=title)
  File "/home/fra/.local/lib/python2.7/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/fra/.local/lib/python2.7/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3745)
  File "/home/fra/.local/lib/python2.7/site-packages/tables/utils.py", line 185, in check_file_access
    check_file_access(filename, 'w')
  File "/home/fra/.local/lib/python2.7/site-packages/tables/utils.py", line 175, in check_file_access
    raise IOError("``%s`` does not exist" % (parentname,))
IOError: ``numerrin_wrapper/tests`` does not exist

----------------------------------------------------------------------
Ran 44 tests in 4.730s

FAILED (errors=1)
```

**Comment by nathanfranklin** [comment]
see simphony/simphony-openfoam#25

**Comment by nathanfranklin** [comment]
@khiltunen , this can be closed too, right?

**Comment by khiltunen** [comment]
Yes this should work now also
